name: Build and Publish J2

on:
  workflow_dispatch:
  pull_request:
   types: [closed]
   paths-ignore:
    - J1/*
    - J3/*
    - J4/*
    - J5/*

jobs:
  Publish_Release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE }}
      
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"
    
      - name: Run `packer init`
        id: init
        run: "packer init ./J2/Packer/docker-voting-app.pkr.hcl"
  
      - name: Run `packer validate`
        id: validate
        run: "packer validate ./J2/Packer/docker-voting-app.pkr.hcl"
  
      - name: Build Artifact
        run: packer build -color=false -on-error=abort ./J2/Packer/docker-voting-app.pkr.hcl