name: Build and Publish J1

on:
  workflow_dispatch:
  pull_request:
   types: [closed]
   paths-ignore:
    - J2/*
    - J3/*
    - J4/*
    - J5/*

jobs:
  SemVer:
    name: Semantic Release Version
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.semantic.outputs.new_release_version }}
      old_version: ${{ steps.semantic.outputs.last_release_version }}
      is_released: ${{ steps.semantic.outputs.new_release_published }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Get Release Version Number
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE }}
  
  Lint_And_Security:
    name: Check Lint and Security of the code
    runs-on: ubuntu-latest
    env:
      working-directory: ./J1
    steps:
      - uses: actions/checkout@v3

      - name: Python Lint
        working-directory: ${{env.working-directory}}
        run: |
          pip install flake8
          flake8 azure-vote/main.py

      - name: Is secure ?
        working-directory: ${{env.working-directory}}
        run: |
          pip install safety
          safety check -r azure-vote/main.py

  Build_And_Publish:
    name: Build Docker Image and Publish to Registry
    runs-on: ubuntu-latest
    needs: [SemVer, Lint_And_Security]
    env:
      working-directory: ./J1
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Build and push
        uses: docker/build-push-action@v4
        if: needs.SemVer.outputs.is_released == 'true'
        with:
          context: ./J1
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:${{ needs.SemVer.outputs.new_version }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        if: needs.SemVer.outputs.is_released == 'false'
        with:
          context: ./J1
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:${{ needs.SemVer.outputs.old_version }}